const BASE_URL = 'https://www.scrapethissite.com'
const START_PAGE_NUMBER = 1
const MILISECONDS_BOUNDARIES = 5000
const MAX_THREADS_NUMBER = 5
const WORKER_TERMINATE_CHECK_TIME_MS = 2000

module.exports = {
    BASE_URL,
    START_PAGE_NUMBER,
    MILISECONDS_BOUNDARIES,
    MAX_THREADS_NUMBER,
    WORKER_TERMINATE_CHECK_TIME_MS,
}
